package Interface;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.ArrayList;   // Para criar a lista de insumos
import java.util.List;  
/**
 *
 * @author arian
 */
public class EmergiaAlface extends javax.swing.JFrame  {
     private List<Insumo> insumos;
    /**
     * Creates new form EmergiaAlface
     */
    public EmergiaAlface() {
        initComponents();
        inicializarInsumos();
    }
     private void desmarcarTodosExceto(JCheckBox selecionado) {
    JCheckBox[] boxes = {AguaIrrigacao, Eletricidade, TrabalhoHumano, Fertilizante, AguadaChuva, Semente,Disel,LuzSolar};
    for (JCheckBox box : boxes) {
        if (box != selecionado) {
            box.setSelected(false);
        }
    }
}
private void inicializarInsumos() {
    insumos = new ArrayList<>();

    insumos.add(new Insumo("A", 146000000000.000)); 
    insumos.add(new Insumo("B", 1600000));          
    insumos.add(new Insumo("C", 1580000));          
    insumos.add(new Insumo("D", 2050000.000));      
    insumos.add(new Insumo("E", 12.600));          
    insumos.add(new Insumo("F", 109000000.000));   
    insumos.add(new Insumo("G", 48000));            
    insumos.add(new Insumo("H", 1000.000));         
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        I = new javax.swing.JPanel();
        AguaIrrigacao = new javax.swing.JCheckBox();
        Eletricidade = new javax.swing.JCheckBox();
        Disel = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        sejunit = new javax.swing.JTextField();
        TrabalhoHumano = new javax.swing.JCheckBox();
        Fertilizante = new javax.swing.JCheckBox();
        LuzSolar = new javax.swing.JCheckBox();
        AguadaChuva = new javax.swing.JCheckBox();
        Semente = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        unidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        B = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        F = new javax.swing.JTextField();
        G = new javax.swing.JTextField();
        H = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        producaomedia = new javax.swing.JTextField();
        Alfacekg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        alfaceha = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        I.setBackground(new java.awt.Color(255, 255, 255));

        AguaIrrigacao.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        AguaIrrigacao.setText("Água de irrigação  ");
        AguaIrrigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguaIrrigacaoActionPerformed(evt);
            }
        });

        Eletricidade.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Eletricidade.setText("Eletricidade");
        Eletricidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EletricidadeActionPerformed(evt);
            }
        });

        Disel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Disel.setText("Diesel");
        Disel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiselActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Coeficiente Emergético");

        sejunit.setEditable(false);
        sejunit.setBackground(new java.awt.Color(255, 255, 255));
        sejunit.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        sejunit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sejunit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        sejunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sejunitActionPerformed(evt);
            }
        });

        TrabalhoHumano.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        TrabalhoHumano.setText("Trabalho Humano");
        TrabalhoHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrabalhoHumanoActionPerformed(evt);
            }
        });

        Fertilizante.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Fertilizante.setText("Fertilizante");
        Fertilizante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FertilizanteActionPerformed(evt);
            }
        });

        LuzSolar.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        LuzSolar.setText("Luz Solar");
        LuzSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuzSolarActionPerformed(evt);
            }
        });

        AguadaChuva.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        AguadaChuva.setText("Água da chuva");
        AguadaChuva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguadaChuvaActionPerformed(evt);
            }
        });

        Semente.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Semente.setText("Semente");
        Semente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SementeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" Selecione e digite a quantidade do Insumo:");

        A.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        A.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A.setText("0");
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Unidade");

        jLabel11.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Quantidade");

        unidade.setEditable(false);
        unidade.setBackground(new java.awt.Color(255, 255, 255));
        unidade.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        unidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Insumo");

        B.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        B.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B.setText("0");
        B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        C.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        C.setText("0");
        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        D.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D.setText("0");
        D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        E.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        E.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        E.setText("0");
        E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        F.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        F.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F.setText("0");
        F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        G.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        G.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        G.setText("0");
        G.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        H.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        H.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H.setText("0");
        H.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Resultado Emergia Alface");

        jLabel13.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Digite a produção média em Kg:");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel2.setText("Sej/ha:");

        producaomedia.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        producaomedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        producaomedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        producaomedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producaomediaActionPerformed(evt);
            }
        });

        Alfacekg.setEditable(false);
        Alfacekg.setBackground(new java.awt.Color(255, 255, 255));
        Alfacekg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Alfacekg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Alfacekg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        Alfacekg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlfacekgActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setText("Sej/Kg:");

        alfaceha.setEditable(false);
        alfaceha.setBackground(new java.awt.Color(255, 255, 255));
        alfaceha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alfaceha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alfaceha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        alfaceha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfacehaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(producaomedia, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(alfaceha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(Alfacekg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alfaceha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(producaomedia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Alfacekg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("MENU");

        calcular.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        calcular.setText("Calcular");
        calcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        limpar.setText("Limpar");
        limpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        sair.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        sair.setText("Sair");
        sair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        anterior.setText("Anterior");
        anterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(115, 115, 115))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anterior)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ILayout = new javax.swing.GroupLayout(I);
        I.setLayout(ILayout);
        ILayout.setHorizontalGroup(
            ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ILayout.createSequentialGroup()
                .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ILayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ILayout.createSequentialGroup()
                                .addComponent(TrabalhoHumano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ILayout.createSequentialGroup()
                                .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AguadaChuva)
                                    .addComponent(Semente)
                                    .addComponent(Disel)
                                    .addComponent(Fertilizante)
                                    .addComponent(AguaIrrigacao)
                                    .addComponent(LuzSolar)
                                    .addComponent(Eletricidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(G, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(H, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ILayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ILayout.createSequentialGroup()
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(ILayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(sejunit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ILayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ILayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ILayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369))
        );
        ILayout.setVerticalGroup(
            ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ILayout.createSequentialGroup()
                .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ILayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(ILayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AguaIrrigacao)
                            .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eletricidade)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sejunit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrabalhoHumano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fertilizante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ILayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AguadaChuva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Semente))
                        .addGap(18, 18, 18)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Disel))
                        .addGap(13, 13, 13)
                        .addGroup(ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LuzSolar)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cálculo Emergia Fórmulas");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n      Para o cálculo da Emergia Total (Sej/ha):\nMultiplicamos a quantidade de cada insumo pelo seu \ncoeficiente emergético.  Ao final Somamos os resultados \nobtemos a Emegia Toatal por hectare.\n\n                                          Fórmula:\n\n Emergia (sej/ha) = quantidade × coeficiente emergético\n\n     Para o cálculo da Emergia específica por kg de alface\nproduzido(sej/kg): \nDividimos a emergia total pelo rendimento médio em Kg.\n\n                                          Fórmula: \n\n                 Emergia por kg de alface (sej/kg) = \nemergia total por hectare (sej/hectare) ÷ rendimento médio ");
        jTextArea1.setSelectionColor(new java.awt.Color(0, 102, 0));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(996, 120));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Simulação calculo Emergia Alface");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setText("Relação de Alguns Insumos necessários no processo ");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel6.setText("da produção da Alface ,suas Transformidades e unidades:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(687, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AguaIrrigacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguaIrrigacaoActionPerformed
         if (AguaIrrigacao.isSelected()) {
         desmarcarTodosExceto(AguaIrrigacao);
        sejunit.setText("1.46E+12"); // Transformidade da Água de irrigação
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         
         if (AguaIrrigacao.isSelected()){
         unidade.setText("L/ha");
         
         }else{
         A.setText("");
         }
        
    }//GEN-LAST:event_AguaIrrigacaoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        A.setText("");
        B.setText("");
        C.setText("");
        D.setText("");
        E.setText("");
        F.setText("");
        G.setText("");
        H.setText("");
        
        producaomedia.setText("");
        sejunit.setText("");
        alfaceha.setText("");
        Alfacekg.setText("");
        unidade.setText("");
        

        // Desmarca os checkboxes
        AguaIrrigacao.setSelected(false);
        Eletricidade.setSelected(false);
        Disel.setSelected(false);
        TrabalhoHumano.setSelected(false);
        Fertilizante.setSelected(false);
        LuzSolar.setSelected(false);
        AguadaChuva.setSelected(false);
        Semente.setSelected(false);
    }//GEN-LAST:event_limparActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
     try {
        // Agrupa os campos de entrada
        JTextField[] camposQuantidade = { A, B, C, D, E, F, G, H };

        // Verifica se há insumos suficientes
        if (insumos.size() < 8) {
            JOptionPane.showMessageDialog(null, "Erro: lista de insumos incompleta.");
            return;
        }

        // Calcula o total de emergia
        double totalEmergia = CalculoEmergia.calcularTotalEmergia(camposQuantidade, insumos);

        // Lê e valida a produção em kg
        String producaoTexto = producaomedia.getText().trim();
        if (producaoTexto.isEmpty()) {
            throw new NumberFormatException("Produção em kg está vazia.");
        }

        double producaoKg = Double.parseDouble(producaoTexto);
        double emergiaPorKg = CalculoEmergia.calcularEmergiaPorKg(totalEmergia, producaoKg);

        // Exibe os resultados nos campos
        alfaceha.setText(String.format("%.3f", totalEmergia));
        Alfacekg.setText(String.format("%.3f", emergiaPorKg));

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Digite um número válido para todas as quantidades e a produção.");
    } catch (ArithmeticException e) {
        JOptionPane.showMessageDialog(null, "Produção em kg não pode ser zero.");
    } catch (IndexOutOfBoundsException e) {
        JOptionPane.showMessageDialog(null, "Erro ao acessar os insumos: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro inesperado: " + e.getMessage());
        e.printStackTrace(); // Opcional, útil para depuração
    }


    }//GEN-LAST:event_calcularActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void sejunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sejunitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sejunitActionPerformed

    private void EletricidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EletricidadeActionPerformed
         if (Eletricidade.isSelected()) {
            desmarcarTodosExceto(Eletricidade);
        sejunit.setText("1.60E+05"); // Transformidade da Água de irrigação
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         if (Eletricidade.isSelected()){
         unidade.setText("KWh/ha");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_EletricidadeActionPerformed

    private void DiselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiselActionPerformed
        if (Disel.isSelected()) {
            desmarcarTodosExceto(Disel);
        sejunit.setText("4.80E+04 "); // Transformidade da Água de irrigação
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
        if (Disel.isSelected()){
         unidade.setText("L/ha");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_DiselActionPerformed

    private void TrabalhoHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrabalhoHumanoActionPerformed
         if (TrabalhoHumano.isSelected()) {
       desmarcarTodosExceto(TrabalhoHumano);
        sejunit.setText("1.58E+06"); // Transformidade da Água de irrigação
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         if (TrabalhoHumano.isSelected()){
         unidade.setText("H/ha");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_TrabalhoHumanoActionPerformed

    private void FertilizanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FertilizanteActionPerformed
         if (Fertilizante.isSelected()) {
    desmarcarTodosExceto(Fertilizante);
        sejunit.setText("2.05E+10 "); // Transformidade da Água de irrigação
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         if (Fertilizante.isSelected()){
         unidade.setText("Kg/ha");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_FertilizanteActionPerformed

    private void LuzSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuzSolarActionPerformed
         if (LuzSolar.isSelected()) {
       desmarcarTodosExceto(LuzSolar);  
        sejunit.setText("1.00E+06"); 
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         if (LuzSolar.isSelected()){
         unidade.setText("MJ");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_LuzSolarActionPerformed

    private void AguadaChuvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguadaChuvaActionPerformed
         if (AguadaChuva.isSelected()) {
     desmarcarTodosExceto(AguadaChuva);
        sejunit.setText("1.26E+04"); 
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         if (AguadaChuva.isSelected()){
         unidade.setText("L/ha");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_AguadaChuvaActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        A.setText("0");
    }//GEN-LAST:event_AActionPerformed

    private void SementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SementeActionPerformed
        if (Semente.isSelected()) {
          desmarcarTodosExceto(Semente);
        sejunit.setText("1.09E+08");
    } else {
        sejunit.setText(""); // Limpa o campo se desmarcar
    }
         if (Semente.isSelected()){
         unidade.setText("g/ha");
         }else{
         unidade.setText("");
         }
        
    }//GEN-LAST:event_SementeActionPerformed

    private void AlfacekgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlfacekgActionPerformed
       Alfacekg.setEditable(false);  // Isso impede edição no campo 
    }//GEN-LAST:event_AlfacekgActionPerformed

    private void alfacehaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfacehaActionPerformed
        alfaceha.setEditable(false);  // Isso impede edição no campo 
    }//GEN-LAST:event_alfacehaActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        EmergiaInicio calculo = new EmergiaInicio(); // cria a próxima janela
    calculo.setVisible(true);                      // mostra a próxima janela
    this.dispose();
    }//GEN-LAST:event_anteriorActionPerformed

    private void producaomediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producaomediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producaomediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmergiaAlface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmergiaAlface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmergiaAlface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmergiaAlface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmergiaAlface().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JCheckBox AguaIrrigacao;
    private javax.swing.JCheckBox AguadaChuva;
    private javax.swing.JTextField Alfacekg;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JCheckBox Disel;
    private javax.swing.JTextField E;
    private javax.swing.JCheckBox Eletricidade;
    private javax.swing.JTextField F;
    private javax.swing.JCheckBox Fertilizante;
    private javax.swing.JTextField G;
    private javax.swing.JTextField H;
    private javax.swing.JPanel I;
    private javax.swing.JCheckBox LuzSolar;
    private javax.swing.JCheckBox Semente;
    private javax.swing.JCheckBox TrabalhoHumano;
    private javax.swing.JTextField alfaceha;
    private javax.swing.JButton anterior;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField producaomedia;
    private javax.swing.JButton sair;
    private javax.swing.JTextField sejunit;
    private javax.swing.JTextField unidade;
    // End of variables declaration//GEN-END:variables
}
