/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicProgressBarUI;
import java.awt.Color;
import java.awt.*;
import javax.swing.JComponent;

/**
 *
 * @author arian
 */
public class EmergiaInicio extends javax.swing.JFrame {
    private int progressoAtual = 0;
    private final int LIMITE = 100;


    /**
     * Creates new form EmergiaSign
     */
    public EmergiaInicio() {
        initComponents();
        personalizarBarraVerde();

  
    }
    

      
       private void personalizarBarraVerde() {
        alfacecrescendo.setUI(new BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(Graphics g, JComponent c) {
                Insets b = alfacecrescendo.getInsets();
                int width = alfacecrescendo.getWidth() - (b.left + b.right);
                int height = alfacecrescendo.getHeight() - (b.top + b.bottom);
                int barWidth = (int) (width * alfacecrescendo.getPercentComplete());

                // Pintar fundo
                g.setColor(Color.LIGHT_GRAY);
                g.fillRect(b.left, b.top, width, height);

                // Pintar barra verde escuro
                g.setColor(new Color(0, 128, 0));
                g.fillRect(b.left, b.top, barWidth, height);

                // Borda da barra
                g.setColor(Color.DARK_GRAY);
                g.drawRect(b.left, b.top, width - 1, height - 1);

                // Texto centralizado
                String texto = alfacecrescendo.getString();
                if (alfacecrescendo.isStringPainted() && texto != null) {
                    FontMetrics fm = g.getFontMetrics();
                    int stringWidth = fm.stringWidth(texto);
                    int stringHeight = fm.getAscent();
                    g.setColor(Color.BLACK);
                    g.drawString(texto, (width - stringWidth) / 2 + b.left,
                                 (height + stringHeight) / 2 + b.top - 2);
                }
            }
        });
    }
    
   
   private void adicionarProgresso(int valor) {
    progressoAtual += valor;
  
    if (progressoAtual > LIMITE) {
        progressoAtual = LIMITE;
       
    }
   
    alfacecrescendo.setValue(progressoAtual);
   alfacecrescendo.setString(progressoAtual + "%");


  


    if (progressoAtual == LIMITE) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Alface.jpeg"));
        JOptionPane.showMessageDialog(this, "Alface pronto para a salada!", 
                                  "Mensagem", JOptionPane.INFORMATION_MESSAGE, icon);
       progressoAtual = 0;
       alfacecrescendo.setValue(progressoAtual);
       alfacecrescendo.setString("0%");//zera a barra novamente
    }
   }
// Adiciona um ActionListener (caso você queira executar algo quando o texto for alterado)
 
    public void jTextArea1actionPerformed(ActionEvent evt) {
        // Aqui você pode colocar o código para desabilitar a edição, por exemplo
        jTextArea1.setEditable(false);
        jTextArea1.setFocusable(false);
        jTextArea1.setHighlighter(null);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sol = new javax.swing.JButton();
        eletricidade = new javax.swing.JButton();
        aguairrigacao = new javax.swing.JButton();
        luzsolar = new javax.swing.JButton();
        fertilizante = new javax.swing.JButton();
        diesel = new javax.swing.JButton();
        trabalhohumano = new javax.swing.JButton();
        semente = new javax.swing.JButton();
        alfacecrescendo = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CenarioSimulacao = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        proximo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nEmergia é a quantidade total de energia (de uma única forma de energia de referência,\ngeralmente a solar) que foi usada, direta ou indiretamente, para produzir um bem ou serviço. Ela \npermite avaliar o “custo energético real” de algo, considerando todas as contribuições do ambiente\ne da sociedade.\n\n🌱 Exemplo da Alface:\nImagine que o alface é uma pizza, e para fazer essa pizza, você precisa de vários ingredientes: \nfarinha,molho, queijo, forno, gás, tempo do pizzaiolo, etc.\n\nAgora, pense no alface crescendo no campo como essa pizza sendo feita:\n\n*O Sol é como o forno ligado o tempo todo.\n*A água da chuva é como a massa da pizza.\n\n*Os nutrientes do solo são como o molho e o queijo. \n*O trator que preparou a terra é como o pizzaiolo que amassou a massa.\n*O trabalhador da lavoura é como o entregador da pizza.\n\nTudo isso gasta energia – energia do Sol, energia dos combustíveis, energia humana, etc.\nA emergia do alface é a soma de toda essa energia, convertida em energia solar \nequivalente, necessária para colocar uma folha de alface no seu prato.\n\n🔎 Resumo simples:\n\nEnergia é o que o alface usa.\nEmergia é tudo o que foi usado para que o alface pudesse usar essa energia.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jTextArea1.setSelectionColor(new java.awt.Color(0, 102, 0));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMERGIA");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agora monte sua Alface");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Clique nos insumos necessários para produção da Alface Até chegar a sua casa!");

        sol.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        sol.setText("Água da Chuva");
        sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solActionPerformed(evt);
            }
        });

        eletricidade.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        eletricidade.setText("Eletricidade");
        eletricidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletricidadeActionPerformed(evt);
            }
        });

        aguairrigacao.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        aguairrigacao.setText("Água de irrigação");
        aguairrigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguairrigacaoActionPerformed(evt);
            }
        });

        luzsolar.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        luzsolar.setText("Luz Solar");
        luzsolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzsolarActionPerformed(evt);
            }
        });

        fertilizante.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        fertilizante.setText("Fertilizante");
        fertilizante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fertilizanteActionPerformed(evt);
            }
        });

        diesel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        diesel.setText("Diesel");
        diesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieselActionPerformed(evt);
            }
        });

        trabalhohumano.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        trabalhohumano.setText("Trabalho Humano");
        trabalhohumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabalhohumanoActionPerformed(evt);
            }
        });

        semente.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        semente.setText("Semente");
        semente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sementeActionPerformed(evt);
            }
        });

        alfacecrescendo.setBackground(new java.awt.Color(204, 255, 204));
        alfacecrescendo.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        alfacecrescendo.setForeground(new java.awt.Color(0, 102, 0));
        alfacecrescendo.setToolTipText("");
        alfacecrescendo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, java.awt.Color.green, null, java.awt.Color.darkGray));
        alfacecrescendo.setStringPainted(true);

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setText("Alface Crescendo...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aguairrigacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eletricidade, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(luzsolar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fertilizante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diesel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(trabalhohumano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(semente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(alfacecrescendo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fertilizante, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(trabalhohumano, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eletricidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aguairrigacao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luzsolar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diesel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alfacecrescendo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setToolTipText("");
        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CenarioSimulacao.setAutoCreateRowSorter(true);
        CenarioSimulacao.setBackground(new java.awt.Color(184, 204, 184));
        CenarioSimulacao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CenarioSimulacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Água de irrigação ", "     3.000.000", "L/ha", "1,46E+12 "},
                {" Semente", "               900", "g/ha", " 1,09E+08 "},
                {" Eletricidade", "              150", "KWh/ha ", " 1,60E+05"},
                {" Diesel", "                75", "L/ha", " 5,09E+15 "},
                {" Fertilizante", "              250", "Kg/ha", " 2,05E+10"},
                {" Luz Solar", "     1.200.000", "MJ", "1,00E+06 "},
                {" Trabalho Humano", "             350", "H/ha", " 1,58E+06"},
                {"Produção Média: ", "               30", "Toneladas", null}
            },
            new String [] {
                "INSUMO", "QTDE.", "UNIDADE", "SEJ/UNIDADE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CenarioSimulacao.setGridColor(new java.awt.Color(255, 255, 255));
        CenarioSimulacao.setSelectionBackground(new java.awt.Color(49, 157, 67));
        jScrollPane2.setViewportView(CenarioSimulacao);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cenário de calculo");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        proximo.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        proximo.setText("Proxímo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel9.setText("Clique em “Próximo” para visualizar todos os detalhes!");

        sair.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\nNa próxima página, você poderá conferir a simulação do cálculo da \nemergia da produção de alface, tanto por quilograma quanto por \nhectare.Além disso,serão apresentados os valores de transformidade \nde cada insumo utilizado nesse processo produtivo.\n\nEssa simulação permite entender o impacto energético envolvido na \nprodução agrícola do alface.");
        jTextArea3.setSelectionColor(new java.awt.Color(0, 102, 0));
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(proximo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(proximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(sair)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        EmergiaAlface calculo = new EmergiaAlface(); // cria a próxima janela
    calculo.setVisible(true);                      // mostra a próxima janela
    this.dispose();      
    }//GEN-LAST:event_proximoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void solActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solActionPerformed
        adicionarProgresso(20); 
    }//GEN-LAST:event_solActionPerformed

    private void eletricidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletricidadeActionPerformed
        adicionarProgresso(10); 
        
    }//GEN-LAST:event_eletricidadeActionPerformed

    private void fertilizanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fertilizanteActionPerformed
       adicionarProgresso(10); 
    }//GEN-LAST:event_fertilizanteActionPerformed

    private void trabalhohumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabalhohumanoActionPerformed
        adicionarProgresso(10); 
    }//GEN-LAST:event_trabalhohumanoActionPerformed

    private void aguairrigacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguairrigacaoActionPerformed
        adicionarProgresso(15); 
    }//GEN-LAST:event_aguairrigacaoActionPerformed

    private void luzsolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzsolarActionPerformed
        adicionarProgresso(15); 
    }//GEN-LAST:event_luzsolarActionPerformed

    private void dieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieselActionPerformed
        adicionarProgresso(10); 
    }//GEN-LAST:event_dieselActionPerformed

    private void sementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sementeActionPerformed
        adicionarProgresso(10); 
    }//GEN-LAST:event_sementeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmergiaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmergiaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmergiaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmergiaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmergiaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CenarioSimulacao;
    private javax.swing.JButton aguairrigacao;
    private javax.swing.JProgressBar alfacecrescendo;
    private javax.swing.JButton diesel;
    private javax.swing.JButton eletricidade;
    private javax.swing.JButton fertilizante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton luzsolar;
    private javax.swing.JButton proximo;
    private javax.swing.JButton sair;
    private javax.swing.JButton semente;
    private javax.swing.JButton sol;
    private javax.swing.JButton trabalhohumano;
    // End of variables declaration//GEN-END:variables
}
